apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-systems
  description: A collection of all Backstage example systems
spec:
  targets:
    - ./systems/reservations-system.yaml
    - ./systems/offers-system.yaml
    - ./systems/data-management-system.yaml
