apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: systems
  description: Everything related to artists
  links:
    - url: http://example.com/domain/systems/
      title: Domain Readme
    - url: http://example.com/domains/systems/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  owner: Code-IT
