apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: reporting-api
  description: UI API to manage vehicles via one admin platform using data management API.   
  tags:
    - reporting
    - api
  links:
    - url: https://bitbucket.codeworldwide.com/projects/CGMB/repos/mb-osp/browse/RAPP.Mercedes.Reporting.API   
      title: Bitbucket Repo
      icon: github
    - url: https://github.com/Kunl19/backstage/edit/master/packages/catalog-model/examples/apis/reporting-api.yaml
      title: API Spec
      icon: code
spec:
  type: sub-system
  lifecycle: production
  owner: team-a
  system: OSP
  definition: |
    Projects:
    
    //Reporting API
    Folder Structure:
    
    //This is where we will add the image
    description: <a href="https://google.com">Testing Landing Page</a>
