apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: reservations
  description: Redundant old UI API 
  tags:
    - reservations
    - api
  links:
    - url: https://bitbucket.codeworldwide.com/projects/CGMB/repos/mb-osp/browse/RAPP.Mercedes.Reservation.API   
      title: Bitbucket Repo
      icon: github
    - url: https://github.com/Kunl19/backstage/blob/master/packages/catalog-model/examples/apis/reservation-api.yaml
      title: API Spec
      icon: code
spec:
  type: sub-system
  lifecycle: redundant
  owner: rapp-mercedes
  system: OSP
  definition: |
    Projects:
    RAPP.Mercedes.KeyManagement 
    
    //Key Management API
    //Managing our Auth Keys and all API’s are using it. 
    
    Folder Structure:
    
    //This is where we will add the image
    description: <a href="https://google.com">Testing Landing Page</a>
