apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: vehicle-data
  description: The vehicle search systems provide Read operations (including filter) to external clients. 
    The Search Engine API includes business logic to transform the results. 
    The Vehicle Data API provides pure filter function to the vehicle data. 
    The vehicle data is stored in a relational database (Amazon Aurora) but also some information, such as the Equipment data, is stored in Elasticache.   
  tags:
    - vehicledata
    - datamanagement
  links:
    - url: https://bitbucket.codeworldwide.com/projects/CGMB/repos/mb-osp/browse/RAPP.Mercedes.DataManagement.API 
      title: Bitbucket Repo
      icon: github
    - url: https://github.com/Kunl19/backstage/blob/master/packages/catalog-model/examples/apis/vehicle-data-api.yaml
      title: API Spec
      icon: code
spec:
  type: sub-system
  lifecycle: production
  owner: rapp-mercedes
  system: OSP
  definition: |
    Projects:
    
    //Data Management API
    //Internally used. Updates VDE and imports vehicles. This API is called from Lambda funcitons. 
    
    Folder Structure:
    
    <a href="https://oneomnicom.sharepoint.com/:w:/r/sites/OSPRetainedTeam/_layouts/15/Doc.aspx?sourcedoc=%7B96D4BBB0-F234-402B-963F-D6BD27E4201D%7D&file=All%20OSP%20projects.docx&action=default&mobileredirect=true">OSP Project file</a>
    <a href="https://oneomnicom.sharepoint.com/sites/OSPRetainedTeam/Shared%20Documents/Forms/AllItems.aspx?originalPath=aHR0cHM6Ly9vbmVvbW5pY29tLnNoYXJlcG9pbnQuY29tLzpmOi9zL09TUFJldGFpbmVkVGVhbS9Fc0NoUmw2bzVNNUdwQUtQZW5Kdnc4UUJSOU5yOFhCWEJLZHBINXBzSnZqNWVnP3J0aW1lPUxidzRqb0YtMlVn&id=%2Fsites%2FOSPRetainedTeam%2FShared%20Documents%2FSystem%20Documentation%2FSystem%20Architecture%2FSubsystems%2FVehicle%20Data%20Extract%2Epng&parent=%2Fsites%2FOSPRetainedTeam%2FShared%20Documents%2FSystem%20Documentation%2FSystem%20Architecture%2FSubsystems">Vehicle Data Extract Image</a>
    
    
